### ISSUE TITLE
memory limit reached

### ISSUE THREAD

**Issue by Zt-freak** [vQFire/MBORijnland#2]
Please help
![image](https://user-images.githubusercontent.com/26248881/70423804-821ec200-1a6e-11ea-82b5-6b9860d45b89.png)

**Comment by vQFire** [comment]
Ik heb he nog niet getest, maar [dit](https://www.groovypost.com/howto/howto/how-to-solve-php-fatal-error-allowed-memory-size-of-8388608-bytes-exhausted/) is letterlijk de eerste link als je de error zoekt
