### ISSUE TITLE
svp aparte repositories aanmaken

### ISSUE THREAD

**Issue by Zt-freak** [vQFire/MBORijnland#7]
Ik wil niet je forum,WesleyShop en andere onnodige code erbijclonen.

@iedereen met dezelfde issue:
`git clone -b DeWerkplekV3--single-branch https://github.com/vQFire/MBORijnland.git`

**Comment by Blopeeey** [comment]
![hxb4775iuot31](https://user-images.githubusercontent.com/45825078/70425260-36b9e300-1a71-11ea-8940-775611851338.jpg)

**Comment by vQFire** [comment]
Ik heb het toegevoegd aan de readme
